---
title: "Reto-02"
output: html_notebook
---
## Inicio al modelaje de datos

### OBJETIVO
- Crear un algoritmo knn

#### REQUISITOS
1. Contar con R studio.
1. Usar la carpeta de trabajo `Sesion08/Reto-02`

#### DESARROLLO
Para nuestro modelo de clasificacion knn seguiremos los siguientes pasos: 
* Usaremos el dataset llamado "diamonds" ya disponible en R con el package ggplot2. 
* Lo guardaremos como data frame como "diamentes". 
* Crearemos un numero aleatorio con el 90% de las filas (llamado random)
* Crearemos una funcion de normalizacion (llamada normalizado)
* Normalizaremos los datos y los guardaremos como diamantes_normalizado
* Extraemos el training set y test set
* Extraemos la segunda columna (variable) y la guardamos como factor, ya que es una variable categorica en lugar de numerica (como diamantes_categoria_target). Haremos la misma conversion para test (diamantes_categoria_test)
* Correremos la funcion de prediccion con knn (gracias al package class)
* Creamos la confusion matrix
* Creamos la funcion de precision y la checamos 

```{r}
library(ggplot2)
library(class)
diamantes <- data.frame(diamonds)
set.seed(100)
random <- sample(1:nrow(diamantes),0.9 * nrow(diamantes))
normalizado <-function(x) { (x -min(x))/(max(x)-min(x))}
diamantes_normalizado <- as.data.frame(lapply(diamantes[,c(1,5,6,7,8,9,10)], normalizado))
diamantes_trainining <- diamantes_normalizado[random,]
diamantes_test <- diamantes_normalizado[-random,] 
diamantes_categoria_target <- as.factor(diamantes[random,2])
diamantes_categoria_test <- as.factor(diamantes[-random,2])
predic <- knn(diamantes_trainining,diamantes_test,cl=diamantes_categoria_target,k=20)
con_mat <- table(predic,diamantes_categoria_test)
precision <- function(x){sum(diag(x)/(sum(rowSums(x)))) * 100}
precision(con_mat)

```

